services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:21000@db:5432/task_db
    depends_on:
      - db

  frontend:
    build:
      context: ./task-manager-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 21000
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
